### PR TITLE
feature: authorization_code grant with public client usage

### PR DESCRIPTION
**Pull request by strehle**
* add PKCE to authorization code (always)
* optional allow to omit client_secret

Both options together allow the authorization_code grant with public usage (no secret in request)

### CODE REVIEW

**Comment by strehle** [comment]
Test

uaac token authcode get -c login --port 7000

Pre-requisit is latest cf-uaa-lib library which supports PKCE and allows to omit secret

**Comment by strehle** [comment]
@Tallicia @torsten-sap I add you to define who could to ruby review.

**Comment by peterhaochen47** [comment]
https://github.com/cloudfoundry/cf-uaa-lib/pull/90 is merged now. Let's bump `cf-uaa-lib` so we can test out this feature.

**Comment by strehle** [comment]
> [cloudfoundry/cf-uaa-lib#90](https://github.com/cloudfoundry/cf-uaa-lib/pull/90) is merged now. Let's bump `cf-uaa-lib` so we can test out this feature.

done

**Comment by peterhaochen47** [comment]
@strehle, thanks!
Question: If as [you said here](https://github.com/cloudfoundry/uaa/pull/2448#issuecomment-1711488932), the PKCE is fully backward compatible (both clients and auth-server have to support it for it to take effect; and the auth request will not fail if one of them does not support it), then what is the purpose of adding the config flag `--[no-]pkce` from the user perspective? Why not just always try to use PKCE?

**Comment by strehle** [comment]
> @strehle, thanks! Manually tested, working as expected, great!
> 
> Question: If as [you said here](https://github.com/cloudfoundry/uaa/pull/2448#issuecomment-1711488932), the PKCE is fully backward compatible (both clients and auth-server have to support it for it to take effect; and the auth request will not fail if one of them does not support it), then what is the purpose of adding the config flag `--[no-]pkce` from the user perspective? Why not just always try to use PKCE?

ok and yes, removed the options so that it is now only creating the PKCE for authorization_code flow

**Comment by Tallicia** [comment]
Is this ready to merge or is there anything else that needs to precede merging this?

**Comment by strehle** [comment]
> Is this ready to merge or is there anything else that needs to precede merging this?

could be merged , FYI: @peterhaochen47

**Pull request merged**
